Add test suite using defmt-test
lpc-rs/lpc8xx-hal pull request #301
Opened 2021-01-06 12:15 UTC by hannobraun

I'd like to easily run tests on all target platforms after making a change, instead of having to manually run examples with different command-line arguments for each target. This pull request adds testing infrastructure based on defmt-test. The test suite only contains some dummy tests right now, to verify that the infrastructure works.

I plan on adding real tests with some changes I'm working on, but I wanted to submit this separately, in case there's anything that needs to be discussed here.

2021-01-06 17:53 UTC, david-sawatzke requested changes
Haven't tested it, but seems mostly ready to merge.

I think this should also be compiled by the CI, so people without all the hardware can at least avoid breaking the test build. If you want to add that in a later PR or have good reason not to do so, feel free to merge it.

2021-01-07 10:00 UTC, hannobraun commented
@david-sawatzke Thanks for the review!

> I think this should also be compiled by the CI, so people without all the hardware can at least avoid breaking the test build. If you want to add that in a later PR or have good reason not to do so, feel free to merge it.

Good point! I didn't think about that because we can't run it on CI (with the current infrastructure), but of course we can build it. I'll change that later.

2021-01-07 10:41 UTC, hannobraun commented
Included building the test suite in the CI build, as requested. Also rebased on master (no changes were necessary).

2021-01-07 17:15 UTC, david-sawatzke approved these changes

2021-01-07 17:15 UTC, merged